const router = require("express").Router();
const userRoute = require("./user.routes");
const authRoutes = require("./auth.routes");
const categoryRoutes = require("./category.routes");
const postRoutes = require("./post.routes");
const messageRoutes = require("./message.routes");
const offerRoutes = require("./offer.routes");
const reviewRoutes = require("./review.routes");
const notificationRoutes = require("./notification.routes");
const contactRoutes = require("./contact.routes");
const healthRoutes = require("./health.routes");
router.use("/notifications", notificationRoutes);
router.use("/contact", contactRoutes);
router.use(healthRoutes);
router.use("/reviews", reviewRoutes);
router.use("/offers", offerRoutes);
router.use("/messages", messageRoutes);
router.use("/", userRoute);
router.use("/auth", authRoutes);
router.use("/categories", categoryRoutes);
router.use("/posts", postRoutes);
module.exports = router;
